dist: xenial
services:
  - docker

matrix:
  include:
    - language: go
      script: echo "TO DO"
    - language: python
      before_script:
        - pip install -r requirements-dev.txt
      script:
        - flake8
        - isort -rc -c -vb
