dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

services:
  - docker

before_install:
  - pip install .
  # For some reason if this is not done before, the image won't be pulled.
  # This is not required when running locally.
  - docker pull alpine/socat:latest

script:
  - python -m unittest discover
